[serviceweaver]
binary = "./onlineboutique"
rollout = "5m"

[single]
listeners.boutique = { address = "localhost:12345" }
listeners.internal = { address = "localhost:12346" }

[multi]
listeners.boutique = { address = "localhost:12345" }
listeners.internal = { address = "localhost:12346" }

[gke]
regions = ["us-west1"]
listeners.boutique = { is_public = true, hostname = "onlineboutique.serviceweaver.dev" }
listeners.internal = { hostname = "onlineboutique.serviceweaver.dev" }
