[package]
name = "workgenerator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
fake = { version = "2.9.2", features = ["derive"] }
rand = "0.8.5"

[build-dependencies]
anyhow = "1.0.86"
serde = "1.0.204"
serde_json = "1.0.122"
